### ISSUE TITLE
插入引用bug

### ISSUE THREAD

**Issue by zhpanvip** [nowandfurure/richeditor#4]
点击插入引用后无法将光标移除引用区。

**Comment by LuZWCHA** [comment]
能具体将手机的型号和Android版本描述下吗，是100%发生还是概率性发生

**Comment by LuZWCHA** [comment]
能将手机的型号和Android版本提供下吗？

**Comment by laizimo** [comment]
请提供一下错误截图，示例截图，手机型号和版本型号，方便我们复现和排查问题，谢谢！@zhpanvip

**Comment by zhpanvip** [comment]
手机型号：魅族MX5 系统版本 Android 5.1  插入引用时候光标只能再引用区无法跳出。






[cid:61de9c9c-0082-42da-9eaf-46d6c3391521]


________________________________
发件人: Lay zimo <notifications@github.com>
发送时间: 2017年12月21日 22:10:45
收件人: nowandfurure/richeditor
抄送: zhpanvip; Mention
主题: Re: [nowandfurure/richeditor] 插入引用bug (#4)


请提供一下错误截图，示例截图，手机型号和版本型号，方便我们复现和排查问题，谢谢！@zhpanvip<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhpanvip&data=02%7C01%7C%7Cb99627795a42495530c508d5487ca13a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636494622478338246&sdata=VXdfO8ZrPICycOCDwtrY%2FYxi6Us7zOTwRCWe%2B5Amuw4%3D&reserved=0>

―

**Comment by LuZWCHA** [comment]
在引用样式的时候通过取消引用样式才能恢复比如H标签或者直接取消，你所说的光标无法移出指的是什么情况？
